import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { NeonAuthUIProvider, UserButton } from "@neondatabase/auth/react";
import { authClient } from "@/lib/auth/client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[var(--background)]">
        <NeonAuthUIProvider
          authClient={authClient as Parameters<typeof NeonAuthUIProvider>[0]["authClient"]}
          redirectTo="/dashboard"
        >
          <header className="border-b border-[var(--border)]">
            <div className="mx-auto flex h-16 w-full max-w-6xl items-center justify-between">
              <Link href={"/"}>Event Planner</Link>
              <nav className="flex items-center gap-4">
                <Link
                  className="text-sm text-[var(--muted-foreground)]"
                  href={"/dashboard"}
                >
                  Dashboard
                </Link>
                <UserButton size="icon" />
              </nav>
            </div>
          </header>

          <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col px-4 py-8">
            {children}
          </main>
        </NeonAuthUIProvider>
      </body>
    </html>
  );
}
